site_name: Docs
repo_url: https://github.com/blekmus/docs
repo_name: blekmus/docs


theme: 
    name: material
    palette:
        scheme: custom
    font:
        text: Noto Sans
        code: Fira Code
    icon:
        repo: fontawesome/brands/github
    logo: assets/logo.png
    features:
        - navigation.instant
        - navigation.top
        - content.code.annotate
        - navigation.tabs

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.smartsymbols
    - pymdownx.critic
    - pymdownx.tasklist:
        custom_checkbox: true
    - footnotes
    - admonition
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.tabbed:
        alternate_style: true 
    - toc:
        permalink: true


plugins:
    - search
    - git-revision-date-localized:
        type: timeago


extra_css:
    - stylesheets/custom.css


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blekmus
      name: Dinil on Github


copyright: Copyright &copy; 2020 - Present. Dinil Fernando


# Page Tree
nav:
    - Home: index.md
    - System:
        - General:      pages/system/general.md
        - Systemd:      pages/system/systemd.md
        - Storage:      pages/system/storage.md
        - Databases:    pages/system/database.md
        - Git:          pages/system/git.md
        - Networking:   pages/system/networking.md
        - Webhooks:     pages/system/webhooks.md

    - Applications:
        - Postfix:      pages/applications/postfix.md
        - Fail2Ban:     pages/applications/fail2ban.md
        - Veracrypt:    pages/applications/veracrypt.md
        - Tor:          pages/applications/tor.md
        - PHP:          pages/applications/php.md
        - Logwatch:     pages/applications/logwatch.md
        - Flask:        pages/applications/flask.md
        - Nginx:        pages/applications/nginx.md
        - Apache:       pages/applications/apache.md
        - React:        pages/applications/react-js.md
        - Rsync:        pages/applications/rsync.md
        - UFW:          pages/applications/ufw.md
        - FFMPEG:       pages/applications/ffmpeg.md
        - Rclone:       pages/applications/rclone.md
        - Laravel:      pages/applications/laravel.md

    - Languages:
        - Javascript:   pages/languages/javascript.md
        - CSS:          pages/languages/css.md

    - Tools: pages/tools.md

    - Other:
        - DuckDuckGo:   pages/other/duckduckgo.md
        - GCalendar:    pages/other/gcalendar.md
        - Hardware:     pages/other/hardware.md


