site_name: Docs
repo_url: https://github.com/fire-walker/docs
repo_name: fire-walker/docs


theme: 
    name: material
    palette:
        scheme: custom
    font:
        text: Noto Sans
        code: Fira Code
    icon:
        repo: fontawesome/brands/github
        logo: octicons/book-16


markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - footnotes
    - admonition
    - pymdownx.betterem:
        smart_enable: all
    - toc:
        permalink: true


plugins:
    - git-revision-date-localized:
        type: timeago


extra_css:
    - stylesheets/custom.css


# Page Tree
nav:
    - Home: index.md
    - System:
        - General:      pages/general.md
        - Storage:      pages/storage.md
        - UFW:          pages/ufw.md
        - Databases:    pages/database.md
        - Git:          pages/git.md
    - Applications:
        - Postfix:      pages/postfix.md
        - Fail2Ban:     pages/fail2ban.md
        - Veracrypt:    pages/veracrypt.md
        - Tor:          pages/tor.md
        - PHP:          pages/php.md
        - Logwatch:     pages/logwatch.md
        - Webhooks:     pages/webhooks.md
        - Flask:        pages/flask.md
        - Nginx:        pages/nginx.md
        - Apache:       pages/apache.md
    - Languages:
        - Python:       pages/python.md
    - Other:
        - DuckDuckGo:   pages/duckduckgo.md

